tracer.property: "I AM THE DEFAULT"
server.port: "8086"

spring.jpa.database: "MYSQL"
spring.datasource.platform:  "mysql"
spring.jpa.show-sql: "false"
spring.database.driver-class-name: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://ec2-3-6-82-226.ap-south-1.compute.amazonaws.com:3306/PTMS_PRODUCT"
spring.datasource.username: "{cipher}1c81a682d3bd1bc738a33856af6b638423b2733e3c0df5f27842265fd5506d7e"
spring.datasource.password: "{cipher}1c81a682d3bd1bc738a33856af6b638423b2733e3c0df5f27842265fd5506d7e"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5Dialect"
spring.jpa.hibernate.naming.physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
spring.cloud.config.server.encrypt.enabled: "false"

redis.server: "localhost"
redis.port: "6379"
signing.key: "{cipher}543e6034087e20441bbbf56991dc59ff725af6c7818a14532dcf2fc2efb0a6c1a36e3a36cbc3fee666ff12d97b07d90f"

management.endpoints.web.exposure.include: "*"
#security.oauth2.resource.userInfoUri: "http://localhost:8901/auth/user"
#signing.key: "alteredcarbons1e7"

eureka.instance.preferIpAddress: "true"
eureka.client.registerWithEureka: "true"
eureka.client.fetchRegistry: "true"
eureka.client.serviceUrl.defaultZone: "https://localhost:8761/eureka/"


###### Email Properties ######
spring.mail.host: "smtp.gmail.com"
spring.mail.port: "587"
spring.mail.properties.mail.smtp.starttls.enable: "true"
spring.mail.username: "donotreply.proarchs"
spring.mail.password: "{cipher}10a525b8cef8cc162e639dacde4305672a8787aacf9124fc45ee8db7f601bde4"
spring.mail.properties.mail.smtp.starttls.required: "true"
spring.mail.properties.mail.smtp.auth: "true"
spring.mail.properties.mail.smtp.connectiontimeout: "5000"
spring.mail.properties.mail.smtp.timeout: "5000"
spring.mail.properties.mail.smtp.writetimeout: "5000"

###External Services URLs
service.auth.jwttype.url: "http://localhost:8901/auth/oauth/token"

config.response.format.exclude.null: "true"

#This will prevent hibernate from looking for hibernate_sequence entries for auto increment on PK
spring.jpa.hibernate.use-new-id-generator-mappings: "false"


#api properties
com.proarchs.product.api.basepath: "/v1.0"
com.proarchs.product.api.name: "product"
